StartupEvents.registry('item', event => {
    event.create('wood_brick')
        .food(food => {
            food.nutrition(0)
            food.saturation(0)
            food.alwaysEdible(true)
        })
    event.create('wood_residue')
    event.create('stone_stick')
    event.create('stone_gear')
    event.create('wood_gear')
    event.create('wire_mesh_filter')
    event.create('void_matter')
    event.create('clean_void_matter')
    event.create('plant_fiber')
    event.create('crushed_clean_void_matter')
    event.create('plant_ball')
    event.create('void_matter_ingot')
    event.create('crushed_void_matter')
    event.create('faded_infused_iron')
    event.create('faded_tainted_gold')
    event.create('clean_void_matter_ingot')
    event.create('aura_wand')
    event.create('naturesaura_core')
    event.create('clean_void_matter_dust')
    event.create('mixed_powder')
    event.create('void_matter_dust')
})

